In [6]:
import numpy as np
import ipyparallel as ipp
%matplotlib inline

In [8]:
rc = ipp.Client()
rc.ids

[0, 1]

In [9]:
rc[1:3].apply_sync(lambda: "hola clase mca")

['hola clase mca']

In [10]:
rc[:].map_sync(lambda x,y,z:x+y+z,range(10),range(10),range(10))

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

In [11]:
dview = rc[:]

In [12]:
rc[0].map_sync(lambda x,y,z: x+y+z, range(5), range(5), range(5))

[0, 3, 6, 9, 12]

#### Funciones
* apply_sync
* map_sync

apply_sync: procedimiento por cada motor y map_sync procedimiento con todos los motores

In [14]:
x = 2**5
#range(int(x**0.5)+1)
#np.arange(int(x**0.5)+1) #calculos más rápidos con numpy
for i in np.arange(int(x**0.5)+1):
    print (x % i)

0
0
0
2
0
2


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: RuntimeWarning: divide by zero encountered in long_scalars


%timeit: calcula el tiempo de la instrucción

In [22]:
%%timeit
x = 2**25
for i in np.arange(int(x**0.5)+1):
    x % i

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: RuntimeWarning: divide by zero encountered in long_scalars
  app.launch_new_instance()


100 loops, best of 3: 3.36 ms per loop


#### Aritmetica modular
* Es un sistema aritmético para clases de equivalencia de números enteros llamadas clases de congruencia. La aritmética modular fue introducida en 1801 por Carl Friedrich Gauss 

In [23]:
np.mod(24,12)

0

In [24]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
np.mod(np.arange(24),12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11], dtype=int32)

In [29]:
%timeit (np.array([hora % 12 for hora in np.arange(24)]))

10000 loops, best of 3: 28.2 µs per loop


In [31]:
for med in np.arange(12,20):
    print (np.mod(np.arange(24), med))

[ 0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12  0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13  0  1  2  3  4  5  6  7  8  9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14  0  1  2  3  4  5  6  7  8]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15  0  1  2  3  4  5  6  7]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16  0  1  2  3  4  5  6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17  0  1  2  3  4  5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18  0  1  2  3  4]


In [33]:
np.mod(12, np.arange(24)[2:])

array([ 0,  0,  0,  2,  0,  5,  4,  3,  2,  1,  0, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12], dtype=int32)

In [32]:
[12 % i for i in np.arange(24)[2:]]

[0, 0, 0, 2, 0, 5, 4, 3, 2, 1, 0, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]

##### Actividad

In [ ]:
dview 

In [18]:
x=2**13
range(int(x**0.5)+1)

range(0, 91)

In [22]:
x=2**13
np.arange(int(x**0.5)+1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90])

In [24]:
x=2**13
for i in np.arange(int(x**0.5)+1):
    print (x % i)

0
0
0
2
0
2
2
2
0
2
2
8
8
2
2
2
0
15
2
3
12
2
8
4
8
17
2
11
16
14
2
8
0
8
32
2
20
15
22
2
32
33
2
22
8
2
4
14
32
9
42
32
28
30
38
52
16
41
14
50
32
18
8
2
0
2
8
18
32
50
2
27
56
16
52
17
60
30
2
55
32
11
74
58
44
32
22
14
8
4
2


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: RuntimeWarning: divide by zero encountered in long_scalars
  app.launch_new_instance()


In [28]:
%%timeit
x=2**13
for i in np.arange(int(x**0.5)+1):
    (x % i)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: RuntimeWarning: divide by zero encountered in long_scalars
  app.launch_new_instance()


The slowest run took 5.24 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 67 µs per loop


In [29]:
%%timeit
x=2**17
for i in np.arange(int(x**0.5)+1)[2:]:
    (x % i)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: RuntimeWarning: divide by zero encountered in long_scalars
  app.launch_new_instance()


1000 loops, best of 3: 237 µs per loop


In [36]:
def PrimeQ0(x):
    import numpy as np
    return all (x % i for i in np.arange(int(x**0.5)+1)[2:])    

In [32]:
PrimeQ0(2**7)

False

In [39]:
dview.apply_sync(PrimeQA, 2**7)

NameError: name 'dview' is not defined

In [38]:
dview = c[:]

NameError: name 'c' is not defined

In [42]:
2**np.arange(7)

array([ 1,  2,  4,  8, 16, 32, 64], dtype=int32)

In [43]:
dview.map_sync(PrimeQA, 2**np.arange(7))

NameError: name 'dview' is not defined

In [44]:
lambda x: all(x % i != 0 for i in np.arange(int(x**0.5)+1)[2:]) and x>1

<function __main__.<lambda>>

In [30]:
c[0].app

NameError: name 'c' is not defined

In [47]:
np.all(np.array([x % i for i in np.arange(int(x**0.5)+1)[2:]]))

False

In [46]:
def PrimeQB(x):
    import numpy as np
    return np.all (x % i for i in np.arange(int(x**0.5)+1)[2:])  

In [48]:
%timeit dview.map_sync(PrimeQB, 2**np.arange(7))

NameError: name 'dview' is not defined

In [49]:
np.mod?

In [50]:
24 % 12

0

In [52]:
np.mod(24, 12)

0

In [53]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [57]:
for med in np.arange(12,20):
    print np.mod(np.arange(24),med)

SyntaxError: invalid syntax (<ipython-input-57-76c958fb87f5>, line 2)

In [54]:
np.mod(np.arange(24),12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11], dtype=int32)

In [59]:
np.mod(12, np.arange(24)[2:])

array([ 0,  0,  0,  2,  0,  5,  4,  3,  2,  1,  0, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12], dtype=int32)

In [62]:
np.arange(24)[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23])

In [65]:
12 % 5

2

In [56]:
np.array([hora % 12 for hora in np.arange(24)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11])

In [66]:
def PrimeQC(x):
    import numpy as np
    lista = np.arange(np.int(x**0.5)+1)[2:]
    residuos = np.mod(x, lista)
    return np.all(residuos)

In [67]:
dview.map_sync(PrimeQB, 2**np.arange[10])

NameError: name 'dview' is not defined

In [68]:
dview.map_sync(PrimeQC, 2**np.arange[10])

NameError: name 'dview' is not defined